# NumPy Arrays
### testing the suitability of NumPy arrays for the Library dataset.

In [1]:
import numpy as np
import pandas as pd

UNCG's Spring Semester 2017 started on 1/9/17 and ended on 5/12/17. According to below, this is 2953 hours.

In [2]:
pd.date_range(start='01-09-2017',end='5-12-2017',freq='h')

DatetimeIndex(['2017-01-09 00:00:00', '2017-01-09 01:00:00',
               '2017-01-09 02:00:00', '2017-01-09 03:00:00',
               '2017-01-09 04:00:00', '2017-01-09 05:00:00',
               '2017-01-09 06:00:00', '2017-01-09 07:00:00',
               '2017-01-09 08:00:00', '2017-01-09 09:00:00',
               ...
               '2017-05-11 15:00:00', '2017-05-11 16:00:00',
               '2017-05-11 17:00:00', '2017-05-11 18:00:00',
               '2017-05-11 19:00:00', '2017-05-11 20:00:00',
               '2017-05-11 21:00:00', '2017-05-11 22:00:00',
               '2017-05-11 23:00:00', '2017-05-12 00:00:00'],
              dtype='datetime64[ns]', length=2953, freq='H')

In [3]:
computerAccessTimes = pd.date_range(start='01-09-2017',end='5-12-2017',freq='h')

In [4]:
type(computerAccessTimes)

pandas.core.indexes.datetimes.DatetimeIndex

The number of machines in the library is dependent on a table of values that correlate primary key to machine name. There are 312 entries.

In [5]:
computerInfo = pd.read_csv(r'../data/libraryMachines.csv')

In [6]:
computerInfo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 4 columns):
machineID      312 non-null int64
machineName    312 non-null object
locationID     312 non-null int64
logonType      312 non-null int64
dtypes: int64(3), object(1)
memory usage: 9.8+ KB


Since each one of these cells will contain the number of minutes a machine is used per hour, a 16-bit integer should be suitable (n <= 60).

In [7]:
computerDataGrid = pd.DataFrame(index=computerAccessTimes,columns=computerInfo.machineName,dtype='int16')

In [11]:
computerDataGrid

machineName         LL10004 LL10003 LL10002 LL10001 TL1001 TL1002 TL1003  \
2017-01-09 00:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 01:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 02:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 03:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 04:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 05:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 06:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 07:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 08:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 09:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 10:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 11:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 12:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 13:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 14:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 15:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 16:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 17:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 18:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 19:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 20:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 21:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 22:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-09 23:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-10 00:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-10 01:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-10 02:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-10 03:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-10 04:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-01-10 05:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
...                     ...     ...     ...     ...    ...    ...    ...   
2017-05-10 19:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-10 20:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-10 21:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-10 22:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-10 23:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 00:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 01:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 02:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 03:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 04:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 05:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 06:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 07:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 08:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 09:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 10:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 11:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 12:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 13:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 14:00:00     NaN     NaN     NaN     NaN    NaN    NaN    NaN   
2017-05-11 15:00:00     NaN     NaN     NaN     

A pandas table with 2953 rows and 312 columns and int16 cells takes 7.1 MB.

In [8]:
computerDataGrid.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2953 entries, 2017-01-09 00:00:00 to 2017-05-12 00:00:00
Freq: H
Columns: 312 entries, LL10004 to MLPL05
dtypes: object(312)
memory usage: 7.1+ MB


a numpy array of 16 bit integers would be 2953 x 312 x 16 x .125 (8 bits per byte)

In [17]:
np.ndarray((2953,312),dtype='int16')

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int16)

In [10]:
print 2953 * 312 * 16 * .125

1842672.0


In [22]:
np.random.randint(61,size=(2953,312))

array([[ 9,  4, 36, ..., 20, 30, 34],
       [ 1, 11,  2, ..., 58, 54, 22],
       [ 1, 56, 47, ...,  0, 52, 18],
       ..., 
       [53, 56, 50, ...,  9, 41, 23],
       [57, 38, 44, ..., 47,  6,  1],
       [32, 34, 36, ..., 19,  1, 16]])